[IMP] medor_ps: extract l10n_be_invoice_bba
coopiteasy/medor pull request #4
Opened 2019-08-14 08:08 UTC by robinkeunen

I extracted this module from product_subscription, I think it's better to have l10n modules outside of generic modules.

2019-08-19 10:13 UTC, houssine78 requested changes
Maybe changing the name of the module to something like l10n_be_res_partner_bba. 
second point i'm not sure they should be a dependency on website_product_subscription

2019-08-20 13:03 UTC, robinkeunen commented
This module is actually a "custom module" for medor. The module name should be medor_custom.

The dependence on  `website_product_subscription` is needed by the template website_product_subscription_templates.xml that adds a link to a gift.

2019-08-21 08:47 UTC, houssine78 commented
ok to rename it medor_custom

2019-08-21 08:48 UTC, houssine78 approved these changes

2019-08-22 12:32 UTC, merged